### ISSUE TITLE
Cannot download FITS files

### ISSUE THREAD

**Issue by pscicluna** [karllark/measured_extcurves#2]
When I attempt to download the data files from box, I receive a message that  the files have been removed or are not available to me. Is there an alternative way of accessing them?

**Comment by karllark** [comment]
Please try it again.  The shared link interface to box changed since I posted the file.  I've update the sharing settings for these files and (hopefully) you should have access to them now.

**Comment by pscicluna** [comment]
Thanks, the download seems to work now :)

**Comment by karllark** [comment]
Great.  Closing this issue.
